spring:
   profiles:
     active:
     - dev
---
server: 
  port: 8200
spring:
   profiles: dev   #开发环境
   application:
     name: springcloud-client-config
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
---
server: 
  port: 8201
spring:
   profiles: test   #开发环境
   application:
     name: springcloud-client-config
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
